# Generated by Django 4.1.7 on 2023-03-14 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bgremove", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.AddField(
            model_name="useractivity",
            name="slug",
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
